# Generated by Django 2.0.2 on 2018-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='u2fregistrationrequest',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
