# Generated by Django 2.1.3 on 2018-11-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='icons/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='applicationversion',
            old_name='delete_key',
            new_name='delete_key_path',
        ),
        migrations.RenameField(
            model_name='applicationversion',
            old_name='delete',
            new_name='delete_path',
        ),
        migrations.RemoveField(
            model_name='applicationversion',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='deviceversion',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='sefirmwarefinalversion',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='sefirmwareosuversion',
            name='display_name',
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_versions', to='api.Icon'),
        ),
    ]
