# Generated by Django 2.0.2 on 2018-02-13 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_u2fregistrationrequest_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='U2FAuthenticationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2f_authentication_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='u2fkey',
            name='version',
            field=models.CharField(default='U2F_V2', max_length=255),
        ),
    ]
